name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use node.js version 16
        uses: actions/setup-node@v2
        with: 
          node-version: 16
      - run: npm install
      - run: npm install -g react-scripts
      - run: npm install react@latest
      - run: npm install react-router-dom
      - run: npm run build --prefix client